version: '3.8'

services:
  # Backend service
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    env_file:
      - ./server/.env
    volumes:
      - ./server:/usr/src/app

  # Frontend service
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - '5173:5173'
    environment:
      - REACT_APP_SERVER_URL=http://server:8080
    depends_on:
      - server
    volumes:
      - ./client:/usr/src/app

volumes:
  mongo-data: